#!/usr/bin/ruby
require_relative "advent2"
raise "Usage: solve <input>" if  ARGV.empty?
puts "Part1: #{Advent2.new(File.new(ARGV.first).read).part1}"
puts "Part2: #{Advent2.new(File.new(ARGV.first).read).part2}"
