#!/usr/bin/ruby
require_relative "advent4"
raise "Usage: solve <puzzle-data>" if  ARGV.empty?
puts "Part1: #{Advent4.new(File.new(ARGV.first).read).part1}"
puts "Part2: #{Advent4.new(File.new(ARGV.first).read).part2}"
