#!/usr/bin/ruby
require_relative 'advent3'
require 'test/unit'
class TestAdvent3 < Test::Unit::TestCase

TestData_1 = <<EOF
467..114..
...*......
..35..633.
......#...
617*......
.....+.58.
..592.....
......755.
...$.*....
.664.598.. 
EOF

  def setup
    @test1_1  = [TestData_1, 4361]
    @test2_1  = [TestData_1, 467835]
  end  

  def test_part1
    assert_equal(@test1_1[1], Advent3.new(@test1_1[0]).part1)
  end

  def test_part2
    assert_equal(@test2_1[1], Advent3.new(@test2_1[0]).part2)
  end
end
